---
title: "Informe Laboratorio 1"
author: "Nombre del Equipo"
date: "Fecha del labotorio"
output: 
  html_document:
    highlight: tango
    theme: spacelab
---

```{r setup, include=FALSE}
# NO CAMBIAR EL BlOQUE
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("ggplot2")
```


## Informe de Laboratorio

#### Cargar los datos:
```{r cargar-datos}

```

## 1

```{r resumen-datos}

```

## 2

```{r extraer-pesos}

```


## 3

```{r grafico-n-varones}

```

## 4

```{r grafico-prop-varones}

```

* * *

# Por su cuenta

```{r cargar-nacimientos}

```


## 1


## 2


## 3


## 4

## Infome de trabajo en equipo

<!--
Para cada miembro del equipo, escriba su nombre, si estuvo o presente en la
sesión de laboratorio, si fue autor en esta semana y su contribución al 
laboratorio (como porcentaje). Los porcentajes deben sumar 100.
-->

| Miembro del equipo      | Presente  | Autor   | Contribución % |
|:------------------------|:---------:|:-------:|---------------:|
| Nombre de miembro 1     | Sí / No   | Sí / No | 25%            |
| Nombre de miembro 2     | Sí / No   | Sí / No | 25%            |
| Nombre de miembro 3     | Sí / No   | Sí / No | 25%            |
| Nombre de miembro 4     | Sí / No   | Sí / No | 25%            |
| Total                   |           |         | 100%           |
