---
title: "Laboratorio 3 - Muestreando distribuciones"
author: "Nombre del Equipo"
date: "Fecha del labotorio"
output: 
  html_document:
    fig_height: 4
    highlight: tango
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library(dplyr)
library(ggplot2)
library(mosaic)
```

***

## Informe de laboratorio

#### Cargar los datos:
```{r load-data}
load(url("https://git.io/ames.RData"))
```

#### Set a seed:
```{r set-seed}

```


## Ejercicios:

#### Ejercicio 1: 

```{r ex1}

```

#### Ejercicio 2: 


```{r ex2}

```


#### Ejercicio 3: 




#### Ejercicio 4: 


```{r ex4}

```


#### Ejercicio 5: 

```{r ex5}

```

#### Ejercicio 6:

```{r ex6}

```

#### Ejercicio 7: 



***

## Por su cuenta:

#### 1: 


```{r oyo1}

```


#### 2: 


```{r oyo2}

```


#### 3: 

```{r oyo23}

```

#### 4: 




***

## Infome de trabajo en equipo

<!--
Para cada miembro del equipo, escriba su nombre, si estuvo o presente en la
sesión de laboratorio, si fue autor en esta semana y su contribución al 
laboratorio (como porcentaje). Los porcentajes deben sumar 100.
-->

| Miembro del equipo      | Presente  | Autor   | Contribución % |
|:------------------------|:---------:|:-------:|---------------:|
| Nombre de miembro 1     | Sí / No   | Sí / No | 25%            |
| Nombre de miembro 2     | Sí / No   | Sí / No | 25%            |
| Nombre de miembro 3     | Sí / No   | Sí / No | 25%            |
| Nombre de miembro 4     | Sí / No   | Sí / No | 25%            |
| Total                   |           |         | 100%           |
